#!/bin/bash
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the setup script"

set-workdir /root/infoblox-lab

# Run Python scripts
cd  /root/infoblox-lab/app-migration-lab/terraform/scripts/
python3 infoblox_vpn_configure.py
sleep 540
python3 get_cnames.py
sleep 20
python3 create_aws_vpn.py
sleep 20
python3 extract_tunnels.py
sleep 20
python3 update_uddi_tunnel.py
sleep 20
python3 enable_propagation_vpc.py

source /root/.bashrc

exit 0